//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daishi.JsonParser.UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Daishi.JsonParser.UnitTests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;snippet-format&quot;: &quot;raw&quot;,
        ///    &quot;total&quot;: 150,
        ///    &quot;start&quot;: 1,
        ///    &quot;page-length&quot;: 10,
        ///    &quot;results&quot;: [
        ///        {
        ///            &quot;index&quot;: 1,
        ///            &quot;uri&quot;: &quot;/lessonplan/JY14E_LP_1.1.1.1.xml&quot;,
        ///            &quot;path&quot;: &quot;fn:doc(\&quot;/lessonplan/JY14E_LP_1.1.1.1.xml\&quot;)&quot;,
        ///            &quot;score&quot;: 2192,
        ///            &quot;confidence&quot;: 0.0712232,
        ///            &quot;fitness&quot;: 0.307883,
        ///            &quot;content&quot;: {
        ///                &quot;lesson_plan&quot;: [
        ///                    {
        ///                        &quot;id&quot;: &quot;JY14E_LP_1.1.1.1&quot;,
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;snippet-format&quot;: &quot;raw&quot;,
        ///    &quot;total&quot;: 150,
        ///    &quot;start&quot;: 1,
        ///    &quot;page-length&quot;: 10,
        ///    &quot;results&quot;: [
        ///        {
        ///            &quot;index&quot;: 1,
        ///            &quot;uri&quot;: &quot;/lessonplan/JY14E_LP_1.1.1.1.xml&quot;,
        ///            &quot;path&quot;: &quot;fn:doc(\&quot;/lessonplan/JY14E_LP_1.1.1.1.xml\&quot;)&quot;,
        ///            &quot;score&quot;: 2192,
        ///            &quot;confidence&quot;: 0.0712232,
        ///            &quot;fitness&quot;: 0.307883,
        ///            &quot;content&quot;: {
        ///                &quot;lesson_plan&quot;: [
        ///                    {
        ///                        &quot;id&quot;: &quot;JY14E_LP_1.1.1.1&quot;,
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSON {
            get {
                return ResourceManager.GetString("JSON", resourceCulture);
            }
        }
    }
}
